### ISSUE TITLE
add suffix/prefix to name of kapp created metadata configmaps to avoid configmap naming collisions

### ISSUE THREAD

**Issue by galamiram** [k14s/kapp#146]
Add the ability to add a default prefix for all kapp application's state `configMap` to differentiate them from other `configMap` stored in the same namespace so it won't conflict with the application's `configMap` :smile_cat: 

- [x]  add suffix apps.k14s.io to config map
- [x]  add functionality for users to opt in to this feature
- [x]  manage backward compatibility 
- [x]  if an app is deployed with this feature opted in via the FQ name env variable, the app should continue to behave like the features has been opted in even if the env flag is unset for subsequent kapp actions on the same app.

---
_(edit: hoist solution for those who searched for the corresponding error message)_
👉🏻  TL;DR. https://carvel.dev/kapp/docs/v0.53.0/configmap-migration/

**Comment by cppforlife** [comment]
@galamiram this one isnt going to be straightforward since we already have kapp out there being used and we do not want to break backwards compat. first step in this issue would be to figure out how we should support existing metadata configmaps and be able to fallback to them when necessary.

**Comment by galamiram** [comment]
@cppforlife What about adding a configurable argument, using the kapp configuration object? something like:
```yaml
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

metadataConfigMapPrefix: some-prefix
```

**Comment by cppforlife** [comment]
that wouldnt quite work because kapp would not know about this config (for a particular app) during kapp ls, kapp inspect, and delete commands.

**Comment by galamiram** [comment]
I guess I should better understand the architecture to come up with a clever solution for this issue. Let me get into the bits and think of something :exclamation:

**Comment by cppforlife** [comment]
i could imagine adding functionality to create new kapp apps with suffix added (e.g. `foo.apps.k14s.io` config map name for `-a foo`), but also have to be able to fall back and search if there is already foo configmap that is marked as a kapp app. effectively this would be a double lookup. check if `foo.apps.k14s.io` exists, otherwise check if `foo` exists (+ marked as app).

there is additional backward compat question if anyone relies on existing configmap naming since new names would be different.

**Comment by galamiram** [comment]
@cppforlife I like this approach.

**Comment by ChristianCiach** [comment]
We are using kapp for a few days now and already encountered this issue.

Fortunately, we don't use `kapp deploy` directly, but execute it from an Ansible playbook instead. As a workaround, I've modified the playbook to always append `.kapp` to the app name given to `kapp deploy -a`. 

I really love kapp, but this design decision seems a bit shortsighted. This is just an accident waiting to happen.

**Comment by renuy** [comment]
Pulling this into our prioritized backlog.

**Comment by neil-hickey** [comment]
Hey Team! I plan on submitting a PR / requesting some help on a PR to drive out a solution for this use case.

The proposal is as follows:

- Always append `.apps.k14s.io` by default globally to the configmap created by apps deployed via `kapp deploy ...`

**Example user flows:** 

**New application with name `foo`:**
  - `kapp deploy -a foo`
  - App name is: `foo`
  - Configmap generated is: `foo.apps.k14s.io`

**Existing application named: `foo` and configmap: `foo`**
  - `kapp deploy -a foo`
  - App generated name: `foo`
  - Configmap generated name: `foo.apps.k14s.io`
  - IF: Existing configmap(s) with name `foo` and marked as a kapp app, configmap(s) will be renamed to `foo.apps.k14s.io`

**Existing application named: `foo` and configmap: `foo.apps.k14s.io`**
  - `kapp deploy -a foo`
  - App generated name: `foo`
  - Configmap generated name: `foo.apps.k14s.io`
  - IF: `foo.apps.k14s.io` already exists and marked as a kapp app configmap: continue
  - ELSE: `foo.apps.k14s.io` already exists and **not** marked as a kapp app configmap, error and prevent the deploy continuing. Suggest to the user that the configmap should be renamed / use the environment variable `USE_EXISTING_CONFIGMAP_NAME=true` to prevent migratation to the newly generated configmap name. 

Considerations:
1. **What is the max length of a configmap name?** 
    The length of a configmap name can be 253 characters as [outlined here](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names).
2. **What if someone / something is relying on the configmap being the old name?**
     In general, this configmap is not a supported outside of the kapp usecase, we will provide an environment variable (`USE_EXISTING_CONFIGMAP_NAME=false`) which can be set to `true` to prevent the app from being migrated, however by default we will rename the configmaps during the first `kapp deploy` with this new kapp version.

---

I also intend to create an issue / submit a PR which helps `kapp-controller` solve a bug with CRDs deployed via kapp to have unique names and be migrated inside a reconciliation loop with calling `kapp rename` every time. [See github issue for more](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/376).

This enables a user flow:

`kapp deploy -a foo.test.dev --prev-app foo-ctrl`

Which

1. migrates the app named `foo-ctrl` to `foo.test.dev` during a deploy 
2. checks that foo.test.dev exists and does not try to migrate
3. utilizes the new suffix (`apps.k14s.io`) to have an app named `foo.test.dev` with configmap `foo.test.dev.apps.k14s.io`

**Comment by renuy** [comment]
Fix available as part of kapp v0.47.0

**Comment by alexfouche** [comment]
Did it ever worked as fixed ? 
I waited and tried all Kapp releases from 0.47 to 0.53, and i still get the Kapp configMap created with the name of my app:

```
kapp-0.53 deploy -a influxdb -n tickstack -c -f "$resources_file"

kapp: Error: Disallowed labels errors:
- Resource 'configmap/influxdb (v1) namespace: tickstack' has a disallowed label 'kapp.k14s.io/is-app'
```

This is created: I see not `.app` or no `-ctrl` or whatever suffix

```
kubectl -n tickstack get cm
NAME               DATA   AGE
influxdb           1      6m42s
kube-root-ca.crt   1      8m9s
```

```
kubectl -n tickstack get cm/influxdb -o yaml
apiVersion: v1
data:
  spec: '{"labelKey":"kapp.k14s.io/app","labelValue":"1663607616581305750","lastChange":{"startedAt":"0001-01-01T00:00:00Z","finishedAt":"0001-01-01T00:00:00Z"},"usedGKs":[]}'
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-19T17:13:36Z"
  labels:
    kapp.k14s.io/is-app: ""
  name: influxdb
  namespace: tickstack
  resourceVersion: "2891638769"
  uid: 7203fe3c-4b46-4c6b-8812-c2177200ece6
```

**Comment by ChristianCiach** [comment]
It is my understanding that Kapp uses the fully qualified configMap names by default now (edit: I may be wrong about that), but existing apps are not automatically migrated to the new naming scheme. This is documented here: https://carvel.dev/kapp/docs/v0.52.0/configmap-migration/

We are deploying with migration enabled (`KAPP_FQ_CONFIGMAP_NAMES=true`) since Kapp 0.47.0 and we didn't encounter any issues yet.

Disclaimer: I am not a maintainer of this project.

**Comment by praveenrewar** [comment]
Hi @alexfouche! Just as @ChristianCiach has pointed out, kapp doesn't use the fully qualified name by default (not yet), as this would be a backward incompatible change for folks who don’t want the new behaviour. We are definitely planning planning to make this as default behaviour down the line.
Please refer to the [docs](https://carvel.dev/kapp/docs/v0.52.0/configmap-migration/) for more details on how to opt in to the new behaviour.

**Comment by alexfouche** [comment]
It works !
Unfortunately i was searching for help within this issue and in `kapp (...) --help` CLI indications.
Hopefully now the link to the doc is within the issue for others to find.
Thank you

**Comment by ChristianCiach** [comment]
To tell the truth: When this got merged back then, I actually learned from the source code how to enable this behavior. I think it was also mentioned on the [release notes](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.47.0). I didn't know this was part of the documention until today..

**Comment by praveenrewar** [comment]
Hmm, that's a good point, we will try to mention the docs link in the issue for such cases :)
